### ISSUE TITLE
Where to add the config params?

### ISSUE THREAD

**Issue by sellrock-de** [BigChicChicken/ApiPlatformSkipNullBundle#1]
Where should i add this? 

`api_platform_skip_null:
    enabled: true|false # (Default: true)`

I tried to add this in api_platform.yaml was not working for me.

**Comment by BigChicChicken** [comment]
> Where should i add this? 
> 
> `api_platform_skip_null:
>     enabled: true|false # (Default: true)`
> 
> I tried to add this in api_platform.yaml was not working for me.

Hello,
You should add this into a file named `api_platform_skip_null.yaml` in your folder `/config/packages`.

I will add it in the Doc.

**Comment by BigChicChicken** [comment]
d568c489aa99bc95e57199d3e848b8c03686bdc8
